MODEL:
  TYPE: effnet
  NUM_CLASSES: 1000
  ACTIVATION_FUN: silu
EN:
  STEM_W: 48
  STRIDES: [1, 2, 2, 2, 1, 2, 1]
  DEPTHS: [3, 5, 5, 7, 7, 9, 3]
  WIDTHS: [24, 40, 64, 128, 176, 304, 512]
  EXP_RATIOS: [1, 6, 6, 6, 6, 6, 6]
  KERNELS: [3, 3, 5, 3, 5, 5, 3]
  HEAD_W: 2048
OPTIM:
  OPTIMIZER: sgd
  LR_POLICY: cos
  BASE_LR: 1.27
  MIN_LR: 0.005
  MAX_EPOCH: 400
  WEIGHT_DECAY: 2.4e-05
  WARMUP_EPOCHS: 5
  EMA_ALPHA: 1e-5
  EMA_UPDATE_PERIOD: 32
  BIAS_USE_CUSTOM_WEIGHT_DECAY: True
  BIAS_CUSTOM_WEIGHT_DECAY: 0.
BN:
  USE_CUSTOM_WEIGHT_DECAY: True
  CUSTOM_WEIGHT_DECAY: 0.
TRAIN:
  DATASET: imagenet
  IM_SIZE: 456
  BATCH_SIZE: 1024
  MIXED_PRECISION: True
  MIXUP_ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  LABEL_SMOOTHING: 0.1
  AUGMENT: AutoAugment
TEST:
  DATASET: imagenet
  IM_SIZE: 522
  BATCH_SIZE: 1024
DATA_LOADER:
  NUM_WORKERS: 10
LOG_PERIOD: 100
NUM_GPUS: 32
