MODEL:
  TYPE: regnet
  NUM_CLASSES: 1000
  ACTIVATION_FUN: silu
  SCALING_TYPE: r
  SCALING_FACTOR: 1.3
REGNET:
  BLOCK_TYPE: res_bottleneck_linear_block
  DEPTH: 28
  W0: 48
  WA: 14.5
  WM: 2.226
  GROUP_W: 8
  BOT_MUL: 4.0
  HEAD_W: 1000
  SE_ON: True
  SE_R: 0.25
OPTIM:
  OPTIMIZER: sgd
  LR_POLICY: cos
  BASE_LR: 1.27
  MIN_LR: 0.005
  MAX_EPOCH: 400
  WEIGHT_DECAY: 2.4e-05
  WARMUP_EPOCHS: 5
  EMA_ALPHA: 1e-5
  EMA_UPDATE_PERIOD: 32
  BIAS_USE_CUSTOM_WEIGHT_DECAY: True
  BIAS_CUSTOM_WEIGHT_DECAY: 0.
BN:
  USE_CUSTOM_WEIGHT_DECAY: True
  CUSTOM_WEIGHT_DECAY: 0.
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 1024
  MIXED_PRECISION: True
  MIXUP_ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  LABEL_SMOOTHING: 0.1
  AUGMENT: AutoAugment
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 1024
DATA_LOADER:
  NUM_WORKERS: 10
LOG_PERIOD: 100
NUM_GPUS: 8
