MODEL:
  TYPE: regnet
  NUM_CLASSES: 1000
REGNET:
  DEPTH: 26
  W0: 88
  WA: 30.3
  WM: 2.404
  GROUP_W: 32
  SE_ON: True
OPTIM:
  OPTIMIZER: sgd
  LR_POLICY: cos
  BASE_LR: 2.54
  MIN_LR: 0.005
  MAX_EPOCH: 400
  WEIGHT_DECAY: 2.4e-05
  WARMUP_EPOCHS: 5
  EMA_ALPHA: 1e-5
  EMA_UPDATE_PERIOD: 32
  BIAS_USE_CUSTOM_WEIGHT_DECAY: True
  BIAS_CUSTOM_WEIGHT_DECAY: 0.
BN:
  USE_CUSTOM_WEIGHT_DECAY: True
  CUSTOM_WEIGHT_DECAY: 0.
TRAIN:
  DATASET: imagenet
  IM_SIZE: 240
  BATCH_SIZE: 2048
  MIXED_PRECISION: True
  MIXUP_ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  LABEL_SMOOTHING: 0.1
  AUGMENT: AutoAugment
TEST:
  DATASET: imagenet
  IM_SIZE: 272
  BATCH_SIZE: 2048
DATA_LOADER:
  NUM_WORKERS: 10
LOG_PERIOD: 100
NUM_GPUS: 8
