MODEL:
  TYPE: anynet
  NUM_CLASSES: 1000
ANYNET:
  BLOCK_TYPE: res_bottleneck_block
  BOT_MULS: [1.0, 1.0, 1.0, 1.0]
  DEPTHS: [2, 7, 20, 2]
  GROUP_WS: [72, 72, 72, 72]
  HEAD_W: 0
  SE_ON: True
  SE_R: 0.25
  STEM_TYPE: simple_stem_in
  STEM_W: 32
  STRIDES: [2, 2, 2, 2]
  WIDTHS: [216, 432, 1152, 2808]
OPTIM:
  OPTIMIZER: sgd
  LR_POLICY: cos
  BASE_LR: 2.54
  MIN_LR: 0.005
  MAX_EPOCH: 400
  WEIGHT_DECAY: 2.4e-05
  WARMUP_EPOCHS: 5
  EMA_ALPHA: 1e-5
  EMA_UPDATE_PERIOD: 32
  BIAS_USE_CUSTOM_WEIGHT_DECAY: True
  BIAS_CUSTOM_WEIGHT_DECAY: 0.
BN:
  USE_CUSTOM_WEIGHT_DECAY: True
  CUSTOM_WEIGHT_DECAY: 0.
TRAIN:
  DATASET: imagenet
  IM_SIZE: 268
  BATCH_SIZE: 2048
  MIXED_PRECISION: True
  MIXUP_ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  LABEL_SMOOTHING: 0.1
  AUGMENT: AutoAugment
TEST:
  DATASET: imagenet
  IM_SIZE: 304
  BATCH_SIZE: 2048
DATA_LOADER:
  NUM_WORKERS: 10
LOG_PERIOD: 100
NUM_GPUS: 32
